name: Terraform AWS OIDC GITHUB Demo
on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION : "us-east-1"   
  WORK_DIR: ./Terraform  # Set your working directory globally
permissions:
      id-token: write
      contents: read

jobs:
  OIDC:
    name: 'OIDC'
    runs-on: ubuntu-latest
    environment: oidc
    defaults:
      run:
        shell: bash
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      # Set up AWS credentials-
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
     
      - name: Terraform format
        id: fmt
        run: terraform fmt
        working-directory: ${{ env.WORK_DIR}}
        
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORK_DIR}}
        
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.WORK_DIR}}

      - uses: actions/github-script@v6
        with:   
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
       
        
      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ${{ env.WORK_DIR}}
        
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORK_DIR}}
        
      - name: Terraform Output
        run: terraform output
        working-directory: ${{ env.WORK_DIR}}
