name: Terraform AWS OIDC GITHUB Demo
on:
  push:
    branches: [ "main" ]
env:
  AWS_REGION : "us-east-1"   
  WORK_DIR: ./Terraform  # Set your working directory globally
permissions:
      id-token: write
      contents: read

jobs:
  OIDC:
    name: 'OIDC'
    runs-on: ubuntu-latest
    environment: oidc
    defaults:
      run:
        shell: bash
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      # Set up AWS credentials-
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
     
      - name: Terraform format
        id: fmt
        run: terraform fmt
        working-directory: ${{ env.WORK_DIR}}
        
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORK_DIR}}
        
      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.WORK_DIR}}

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ${{ env.WORK_DIR}}

      - uses: actions/github-script@v6
        with:
          script: |
            const outcomeFmt = `${{ steps.fmt.outcome }}`;
            const outcomeInit = `${{ steps.init.outcome }}`;
            const outcomeValidate = `${{ steps.validate.outcome }}`;
            const outcomePlan = `${{ steps.plan.outcome }}`;
            const validateOutput = `${{ steps.validate.outputs.stdout }}`;
            ## const planOutput = `${{ steps.plan.outputs.plan_output }}`;
            
            const output = `#### Terraform Format and Style 🖌 ${outcomeFmt}`;
            console.log(output);
      
            const initOutput = `#### Terraform Initialization ⚙️ ${outcomeInit}`;
            console.log(initOutput);
      
            const validateStatus = `#### Terraform Validation 🤖 ${outcomeValidate}`;
            console.log(validateStatus);
      
            const detailsMarkup = `
            <details>
              <summary>Validation Output</summary>
              \`\`\`
              ${validateOutput}
              \`\`\`
            </details>
            `;
            console.log(detailsMarkup);

                  
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORK_DIR}}
        
      - name: Terraform Output
        run: terraform output
        working-directory: ${{ env.WORK_DIR}}
